Generated from base-vm

diff --git a/.github/workflows/test.yml b/.github/workflows/test.yml
--- a/.github/workflows/test.yml
+++ b/.github/workflows/test.yml
@@ -30,18 +30,20 @@ jobs:
       fail-fast: false
       matrix:
         release: [ "9.0", "9.1", "9.2", "9.3", "9.4", "10.0", "10.1", ""]
-        arch: [ "aarch64", ""]
+        arch: [ "aarch64", "", "riscv64"]
         runs: [ "ubuntu-24.04", "ubuntu-24.04-arm"]
         exclude:
           - runs: "ubuntu-24.04-arm"
             arch: ""
+          - runs: "ubuntu-24.04-arm"
+            arch: "riscv64"
 
     runs-on: ${{ matrix.runs }}
     name: sshfs NetBSD
     env:
       MYTOKEN : ${{ secrets.MYTOKEN }}
       MYTOKEN2: "value2"
-      SEC_VBOX : ${{ secrets.SEC_VBOX }}
+      SEC_VBOX : ${{ vars.SEC_VBOX }}
       DEBUG: 1
     steps:
     - uses: actions/checkout@v4
@@ -64,9 +66,14 @@ jobs:
           echo "arch is empty"
           echo "run=true" >> $GITHUB_OUTPUT
         elif [ -e "conf/${_release}-${_arch}.conf" ]; then
-          #ok, go ahead
           echo "conf exists: conf/${_release}-${_arch}.conf"
-          echo "run=true" >> $GITHUB_OUTPUT
+          #ok, go ahead
+          if [[ "$(echo "NetBSD" | tr '[:upper:]' '[:lower:]')-${_arch}" == "freebsd-riscv64" ]]; then
+            echo "The NetBSD-${_arch} doesn't support sshfs, skip."
+            echo "run=false" >> $GITHUB_OUTPUT
+          else
+            echo "run=true" >> $GITHUB_OUTPUT
+          fi
         else
           echo "The release ${_release} doesn't support ${_arch}, skip."
           echo "run=false" >> $GITHUB_OUTPUT
@@ -81,7 +88,7 @@ jobs:
     - name: Test in NetBSD
       if: ${{ steps.check.outputs.run == 'true' }}
       id: test
-      uses: vmactions/netbsd-vm@8db8cdbbbf197f0392101cba8ef647e4c4a1aa9e
+      uses: vmactions/netbsd-vm@b97acdac21b86d298316086be5dc0f5c2b072f99
       with:
         envs: 'DEBUG MYTOKEN MYTOKEN2'
         prepare: |
@@ -149,18 +156,20 @@ jobs:
       fail-fast: false
       matrix:
         release: [ "9.0", "9.1", "9.2", "9.3", "9.4", "10.0", "10.1", ""]
-        arch: [ "aarch64", ""]
+        arch: [ "aarch64", "", "riscv64"]
         runs: [ "ubuntu-24.04", "ubuntu-24.04-arm"]
         exclude:
           - runs: "ubuntu-24.04-arm"
             arch: ""
+          - runs: "ubuntu-24.04-arm"
+            arch: "riscv64"
 
     runs-on: ${{ matrix.runs }}
     name: nfs NetBSD
     env:
       MYTOKEN : ${{ secrets.MYTOKEN }}
       MYTOKEN2: "value2"
-      SEC_VBOX : ${{ secrets.SEC_VBOX }}
+      SEC_VBOX : ${{ vars.SEC_VBOX }}
       DEBUG: 1
     steps:
     - uses: actions/checkout@v4
@@ -185,7 +194,12 @@ jobs:
         elif [ -e "conf/${_release}-${_arch}.conf" ]; then
           #ok, go ahead
           echo "conf exists: conf/${_release}-${_arch}.conf"
-          echo "run=true" >> $GITHUB_OUTPUT
+          if [[ "$(echo "NetBSD" | tr '[:upper:]' '[:lower:]')-${_arch}" == "freebsd-riscv64" ]]; then
+            echo "The NetBSD-${_arch} doesn't support nfs, skip."
+            echo "run=false" >> $GITHUB_OUTPUT
+          else
+            echo "run=true" >> $GITHUB_OUTPUT
+          fi
         else
           echo "The release ${_release} doesn't support ${_arch}, skip."
           echo "run=false" >> $GITHUB_OUTPUT
@@ -200,7 +214,7 @@ jobs:
     - name: Test in NetBSD
       if: ${{ steps.check.outputs.run == 'true' }}
       id: test
-      uses: vmactions/netbsd-vm@8db8cdbbbf197f0392101cba8ef647e4c4a1aa9e
+      uses: vmactions/netbsd-vm@b97acdac21b86d298316086be5dc0f5c2b072f99
       with:
         envs: 'DEBUG MYTOKEN MYTOKEN2'
         prepare: |
@@ -261,25 +275,26 @@ jobs:
 
 
 
-
-
-  test:
+  testscp:
     strategy:
       fail-fast: false
       matrix:
         release: [ "9.0", "9.1", "9.2", "9.3", "9.4", "10.0", "10.1", ""]
-        arch: [ "aarch64", ""]
+        arch: [ "aarch64", "", "riscv64"]
         runs: [ "ubuntu-24.04", "ubuntu-24.04-arm"]
         exclude:
           - runs: "ubuntu-24.04-arm"
             arch: ""
+          - runs: "ubuntu-24.04-arm"
+            arch: "riscv64"
 
     runs-on: ${{ matrix.runs }}
-    name: NetBSD
+    name: scp NetBSD
     env:
       MYTOKEN : ${{ secrets.MYTOKEN }}
       MYTOKEN2: "value2"
-      SEC_VBOX : ${{ secrets.SEC_VBOX }}
+      SEC_VBOX : ${{ vars.SEC_VBOX }}
+      DEBUG: 1
     steps:
     - uses: actions/checkout@v4
     - name: Check arch
@@ -308,10 +323,135 @@ jobs:
           echo "The release ${_release} doesn't support ${_arch}, skip."
           echo "run=false" >> $GITHUB_OUTPUT
         fi
+    - name: Creating Web console
+      if: ${{ steps.check.outputs.run == 'true' }}
+      uses: vmactions/cf-tunnel@v0
+      id: tunnel
+      with:
+        protocol: http
+        port: 8000
     - name: Test in NetBSD
       if: ${{ steps.check.outputs.run == 'true' }}
       id: test
-      uses: vmactions/netbsd-vm@8db8cdbbbf197f0392101cba8ef647e4c4a1aa9e
+      uses: vmactions/netbsd-vm@b97acdac21b86d298316086be5dc0f5c2b072f99
+      with:
+        envs: 'DEBUG MYTOKEN MYTOKEN2'
+        prepare: |
+          /usr/sbin/pkg_add curl
+        release: ${{ matrix.release }}
+        arch: ${{ matrix.arch }}
+        nat: |
+          "10022": "22"
+          "8080": "80"
+          "8443": "443"
+          udp:"8081": "80"
+        usesh: true
+        sync: scp
+        run: |
+          ls -lah /root/work
+          #don't use tree here, freebsd riscv64 doesn't have a tree
+          #tree $HOME/work/
+          if [ -z "$(ls -A $HOME/work)" ]; then
+            echo "nfs error."
+            exit 1
+          fi
+          env
+          echo "TEST_ENV=abc" >>${GITHUB_ENV}
+          cd $GITHUB_WORKSPACE;
+          ls -lah
+          whoami
+          env
+          /sbin/sysctl hw.model
+          /sbin/sysctl hw.ncpu
+          /sbin/sysctl hw.physmem
+          /sbin/sysctl hw.usermem
+          /usr/bin/vmstat
+
+
+    - name: Test NAT
+      if: ${{ steps.check.outputs.run == 'true' }}
+      run:
+        echo "TEST_ENV=$TEST_ENV"
+        [ "$TEST_ENV" = "abc" ]
+        ssh -vvv -p 10022 -i $HOME/.ssh/host.id_rsa root@localhost "uname -a;whoami;pwd"
+    - name: Test custom shell
+      if: ${{ steps.check.outputs.run == 'true' }}
+      shell: netbsd {0}
+      run: |
+        pwd
+        cd $GITHUB_WORKSPACE;
+        pwd
+          cd $GITHUB_WORKSPACE;
+          ls -lah
+          whoami
+          env
+          /sbin/sysctl hw.model
+          /sbin/sysctl hw.ncpu
+          /sbin/sysctl hw.physmem
+          /sbin/sysctl hw.usermem
+          /usr/bin/vmstat
+
+
+
+
+
+
+  test:
+    strategy:
+      fail-fast: false
+      matrix:
+        release: [ "9.0", "9.1", "9.2", "9.3", "9.4", "10.0", "10.1", ""]
+        arch: [ "aarch64", "", "riscv64"]
+        runs: [ "ubuntu-24.04", "ubuntu-24.04-arm"]
+        exclude:
+          - runs: "ubuntu-24.04-arm"
+            arch: ""
+          - runs: "ubuntu-24.04-arm"
+            arch: "riscv64"
+
+    runs-on: ${{ matrix.runs }}
+    name: NetBSD
+    env:
+      MYTOKEN : ${{ secrets.MYTOKEN }}
+      MYTOKEN2: "value2"
+      SEC_VBOX : ${{ vars.SEC_VBOX }}
+    steps:
+    - uses: actions/checkout@v4
+    - name: Check arch
+      id: check
+      run: |
+        _release="${{ matrix.release }}"
+        if [ -z "$_release" ]; then
+          . conf/default.release.conf
+          _release="$DEFAULT_RELEASE"
+        fi
+
+        _arch="${{ matrix.arch }}"
+        if [ "${_arch}" = "x86_64" ]; then
+          _arch=""
+        fi
+
+        if [ -z "${_arch}" ]; then
+          #ok, go ahead
+          echo "arch is empty"
+          echo "run=true" >> $GITHUB_OUTPUT
+        elif [ -e "conf/${_release}-${_arch}.conf" ]; then
+          #ok, go ahead
+          echo "conf exists: conf/${_release}-${_arch}.conf"
+          if [[ "$(echo "NetBSD" | tr '[:upper:]' '[:lower:]')-${_arch}" == "freebsd-riscv64" ]]; then
+            echo "The NetBSD-${_arch} doesn't support rsync, skip."
+            echo "run=false" >> $GITHUB_OUTPUT
+          else
+            echo "run=true" >> $GITHUB_OUTPUT
+          fi
+        else
+          echo "The release ${_release} doesn't support ${_arch}, skip."
+          echo "run=false" >> $GITHUB_OUTPUT
+        fi
+    - name: Test in NetBSD
+      if: ${{ steps.check.outputs.run == 'true' }}
+      id: test
+      uses: vmactions/netbsd-vm@b97acdac21b86d298316086be5dc0f5c2b072f99
       with:
         envs: 'MYTOKEN MYTOKEN2'
         prepare: |
