Generated from base-vm

diff --git a/.github/workflows/test.yml b/.github/workflows/test.yml
--- a/.github/workflows/test.yml
+++ b/.github/workflows/test.yml
@@ -47,7 +47,7 @@ jobs:
         port: 8000
     - name: Test in NetBSD
       id: test
-      uses: vmactions/netbsd-vm@2d5f81dcb07b2aee8fd9b85f9951ec9e1ac1a03c
+      uses: vmactions/netbsd-vm@5702d7a8141c15f6982c5198b54cdbe4e090c13c
       with:
         envs: 'DEBUG MYTOKEN MYTOKEN2'
         prepare: |
@@ -101,6 +101,82 @@ jobs:
           /usr/bin/vmstat
 
 
+  testnfs:
+    strategy:
+      matrix:
+        release: [ "9.0", "9.1", "9.2", "9.3", "9.4", "10.0", "10.1", ""]
+        runs: [ "ubuntu-22.04", "ubuntu-24.04", "ubuntu-latest"]
+    runs-on: ${{ matrix.runs }}
+    name: nfs NetBSD
+    env:
+      MYTOKEN : ${{ secrets.MYTOKEN }}
+      MYTOKEN2: "value2"
+      SEC_VBOX : ${{ secrets.SEC_VBOX }}
+      DEBUG: 1
+    steps:
+    - uses: actions/checkout@v4
+    - name: Creating Web console
+      uses: vmactions/cf-tunnel@v0
+      id: tunnel
+      with:
+        protocol: http
+        port: 8000
+    - name: Test in NetBSD
+      id: test
+      uses: vmactions/netbsd-vm@5702d7a8141c15f6982c5198b54cdbe4e090c13c
+      with:
+        envs: 'DEBUG MYTOKEN MYTOKEN2'
+        prepare: |
+          /usr/sbin/pkg_add curl
+        release: ${{ matrix.release }}
+        nat: |
+          "10022": "22"
+          "8080": "80"
+          "8443": "443"
+          udp:"8081": "80"
+        usesh: true
+        sync: nfs
+        run: |
+          ls -lah /root/work
+          tree $HOME/work/
+          if [ -z "$(ls -A $HOME/work)" ]; then
+            echo "nfs error."
+            exit 1
+          fi
+          echo "TEST_ENV=abc" >>${GITHUB_ENV}
+          pwd
+          ls -lah
+          whoami
+          env
+          /sbin/sysctl hw.model
+          /sbin/sysctl hw.ncpu
+          /sbin/sysctl hw.physmem
+          /sbin/sysctl hw.usermem
+          /usr/bin/vmstat
+
+
+    - name: Test NAT
+      run:
+        echo "TEST_ENV=$TEST_ENV"
+        [ "$TEST_ENV" = "abc" ]
+        ssh -vvv -p 10022 -i $HOME/.ssh/host.id_rsa root@localhost "uname -a;whoami;pwd"
+    - name: Test custom shell
+      shell: netbsd {0}
+      run: |
+        pwd
+        cd $GITHUB_WORKSPACE;
+        pwd
+          pwd
+          ls -lah
+          whoami
+          env
+          /sbin/sysctl hw.model
+          /sbin/sysctl hw.ncpu
+          /sbin/sysctl hw.physmem
+          /sbin/sysctl hw.usermem
+          /usr/bin/vmstat
+
+
 
   test:
     strategy:
@@ -117,7 +193,7 @@ jobs:
     - uses: actions/checkout@v4
     - name: Test in NetBSD
       id: test
-      uses: vmactions/netbsd-vm@2d5f81dcb07b2aee8fd9b85f9951ec9e1ac1a03c
+      uses: vmactions/netbsd-vm@5702d7a8141c15f6982c5198b54cdbe4e090c13c
       with:
         envs: 'MYTOKEN MYTOKEN2'
         prepare: |
