Generated from base-vm

diff --git a/.github/workflows/test.yml b/.github/workflows/test.yml
--- a/.github/workflows/test.yml
+++ b/.github/workflows/test.yml
@@ -575,6 +575,75 @@ jobs:
 
 
 
+  testerr:
+    strategy:
+      fail-fast: false
+    runs-on: ubuntu-24.04
+    name: test default error NetBSD
+    env:
+      MYTOKEN : ${{ secrets.MYTOKEN }}
+      MYTOKEN2: "value2"
+      SEC_VBOX : ${{ vars.SEC_VBOX }}
+      GH_TOKEN: ${{ secrets.GH_TOKEN }}
+    steps:
+    - uses: actions/checkout@v6
+    - name: Test in NetBSD
+      id: testerr
+      continue-on-error: true 
+      uses: vmactions/netbsd-vm@7f1b24c6c7562694809f054bb5ca1b5d45a1e8cc
+      with:
+        envs: 'MYTOKEN MYTOKEN2'
+        prepare: |
+          /usr/sbin/pkg_add curl
+        mem: 4096
+        usesh: true
+        debug: true
+        run: |
+          echo "this is an error"
+          exit 1
+    - name: Verify that the previous step failed
+      if: steps.testerr.outcome != 'failure'
+      run: |
+        echo "The step was expected to fail, but it succeeded!"
+        exit 1
+
+  testpass:
+    strategy:
+      fail-fast: false
+    runs-on: ubuntu-24.04
+    name: test default success NetBSD
+    env:
+      MYTOKEN : ${{ secrets.MYTOKEN }}
+      MYTOKEN2: "value2"
+      SEC_VBOX : ${{ vars.SEC_VBOX }}
+      GH_TOKEN: ${{ secrets.GH_TOKEN }}
+    steps:
+    - uses: actions/checkout@v6
+    - name: Test in NetBSD
+      id: testpass
+      continue-on-error: true 
+      uses: vmactions/netbsd-vm@7f1b24c6c7562694809f054bb5ca1b5d45a1e8cc
+      with:
+        envs: 'MYTOKEN MYTOKEN2'
+        prepare: |
+          /usr/sbin/pkg_add curl
+        mem: 4096
+        usesh: true
+        debug: true
+        run: |
+          echo "this is a normal command"
+          exit 0
+    - name: Verify that the previous step succeeded
+      if: steps.testpass.outcome != 'success'
+      run: |
+        echo "The step was expected to succeed, but it failed!"
+        exit 1
+
+
+
+
+
+
 
 
 
